channels:
  - defaults
  - anaconda
  - conda-forge
dependencies:
  - python=3.10.13
  - pip
  - pip:
      - azureml-mlflow==1.55.0
      - azure-ai-ml==1.13.0
      - pyarrow==15.0.0
      - scikit-learn==1.3.0
      - pandas==2.2.1
      - joblib==1.3.2
      - matplotlib==3.8.3
      - >-
        git+https://github.com/microsoft/AzureML-Observability#subdirectory=aml-obs-client
      - >-
        git+https://github.com/microsoft/AzureML-Observability#subdirectory=aml-obs-collector
