channels:
  - defaults
  - anaconda
  - conda-forge
dependencies:
  - python=3.10.13
  - pip
  - pip:
      - azureml-mlflow==1.38.0
      - azure-ai-ml==1.0.0
      - pyarrow==10.0.0
      - scikit-learn==0.24.1
      - matplotlib==3.8.3
      - attrs==23.2.0
      - certifi==2023.11.17
      - charset-normalizer==3.3.2
      - clearml==1.13.2
      - furl==2.1.3
      - idna==3.6
      - joblib==1.3.2
      - jsonschema==4.20.0
      - jsonschema-specifications==2023.12.1
      - numpy==1.26.3
      - orderedmultidict==1.0.1
      - pandas==2.1.4
      - pathlib2==2.3.7.post1
      - pillow==10.2.0
      - psutil==5.9.7
      - PyJWT==2.8.0
      - pyparsing==3.1.1
      - python-dateutil==2.8.2
      - pytz==2023.3.post1
      - PyYAML==6.0.1
      - referencing==0.32.1
      - requests==2.31.0
      - rpds-py==0.16.2
      - scikit-learn==1.3.2
      - scipy==1.11.4
      - setuptools==68.2.2
      - six==1.16.0
      - threadpoolctl==3.2.0
      - tzdata==2023.4
      - urllib3==2.1.0
      - wheel==0.41.2
      - git+https://github.com/microsoft/AzureML-Observability#subdirectory=aml-obs-client
      - git+https://github.com/microsoft/AzureML-Observability#subdirectory=aml-obs-collector