$schema: https://azuremlschemas.azureedge.net/latest/environment.schema.json
name: basic-train-env
image: mcr.microsoft.com/azureml/openmpi3.1.2-ubuntu18.04
conda_file: ../../../Basic_job/environment/environment.yml
description: Environment created from a Docker image plus Conda environment to basic job model.